# SwiftLint Configuration File

# Opt-in rules you might want to enable:
opt_in_rules:
  - anyobject_protocol
  - attributes
  - closure_end_indentation
  - closure_spacing
  - collection_alignment
  - contains_over_first_not_nil
  - empty_collection_literal
  - empty_count
  - explicit_init
  - fatal_error_message
  - force_unwrapping
  - function_default_parameter_at_end
  - implicitly_unwrapped_optional
  - joined_default_parameter
  - let_var_whitespace
  - literal_expression_end_indentation
  - modifier_order
  - multiline_arguments
  - multiline_function_chains
  - operator_usage_whitespace
  - overridden_super_call
  - private_action
  - private_outlet
  - prohibited_super_call
  - redundant_nil_coalescing
  - redundant_type_annotation
  - required_enum_case
  - single_test_class
  - sorted_first_last
  - switch_case_on_newline
  - toggle_bool
  - trailing_closure
  - unavailable_function
  - unneeded_parentheses_in_closure_argument
  - yoda_condition

# Disabled rules you may want to enable for stricter style:
disabled_rules:
  - line_length
  - trailing_whitespace
  - file_length
  - type_body_length
  - function_body_length
  - identifier_name
  - todo

# Customize rules as needed:
line_length:
  warning: 120
  error: 200

excluded:
  - Carthage
  - Pods
  - fastlane
  - build
  - .build
  - .git
  - .github
  - AnilistAPI


# You can add more configuration here as your project grows.
reporter: "xcode"